// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Location, LocationT } from './my-game/location.js';
export { Person, PersonT } from './my-game/person.js';
